//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer1
    {
        public Customer1()
        {
            this.Note1 = new HashSet<Note1>();
        }
    
        public decimal CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<Note1> Note1 { get; set; }
    }
}
